export const resources = [
    {
        id: 1,
        topic: "CSS",
        video_link: null,
        docs_link: "https://www.w3schools.com/cssref/css3_pr_justify-content.asp",
        description: "This document explains how to use justify-content",
    },
    {
        id: 2,
        topic: "CSS",
        video_link: null,
        docs_link: "https://css-tricks.com/snippets/css/a-guide-to-flexbox/",
        description: "This document explains how to use flexbox",
    },
    {
        id: 3,
        topic: "CSS",
        video_link: null,
        docs_link: "https://www.w3schools.com/html/html_css.asp",
        description: "This document gives a basic overview of CSS styling",
    },
    {
        id: 4,
        topic: "CSS",
        video_link: "https://www.youtube.com/watch?v=HxztHgRN8I4",
        docs_link: null,
        description: "This video explains how to use rgb colours in CSS",
    },
    {
        id: 5,
        topic: "CSS",
        video_link: "https://www.youtube.com/watch?v=hyAeX0p-uIA",
        docs_link: null,
        description: "This video explains how to size different objects using CSS",
    },
    {
        id: 6,
        topic: "CSS",
        video_link: "https://www.youtube.com/watch?v=1PnVor36_40",
        docs_link: null,
        description: "This video gives a short overview of CSS skills",
    },
    {
        id: 7,
        topic: "HTML",
        video_link: null,
        docs_link: "https://www.w3schools.com/html/html_basic.asp",
        description: "This document teaches you the basics of how to set up your very own HTML document!",
    },
    {
        id: 8,
        topic: "HTML",
        video_link: null,
        docs_link: "https://developer.mozilla.org/en-US/docs/Learn/Forms",
        description: "This document teaches you how to create forms using HTML",
    },
    {
        id: 9,
        topic: "HTML",
        video_link: null,
        docs_link: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button",
        description: "This document teaches you how to create a button tag using HTML",
    },
    {
        id: 10,
        topic: "HTML",
        video_link: "https://www.youtube.com/watch?v=MDLn5-zSQQI",
        docs_link: null,
        description: "This video gives a short overview of basic HTML skills",
    },
    {
        id: 11,
        topic: "HTML",
        video_link: "https://www.youtube.com/watch?v=y4gWr2fya0I",
        docs_link: null,
        description: "This video gives a short overview of basic HTML skills",
    },
    {
        id: 12,
        topic: "HTML",
        video_link: "https://www.youtube.com/watch?v=tv6bxtCjqDI",
        docs_link: null,
        description: "This video teaches you about some of the most common tags used in HTML",
    },
    {
        id: 13,
        topic: "React",
        video_link: "https://www.youtube.com/watch?v=hQAHSlTtcmY",
        docs_link: null,
        description: "This video covers create-react-app, components, state, props, rendering, event handling, and so much more.",
    },
    {
        id: 14,
        topic: "React",
        video_link: "https://www.youtube.com/watch?v=Ke90Tje7VS0",
        docs_link: null,
        description: "This video provides the introduction to react where you learn what react is, setting up a react app and rendering lists.",
    },
    {
        id: 15,
        topic: "React",
        video_link: "https://www.youtube.com/watch?v=w7ejDZ8SWv8",
        docs_link: null,
        description: "This video will be building a task tracker app and look at components, props, state, hooks, working with an API and more.",
    },
    {
        id: 16,
        topic: "React",
        video_link: null,
        docs_link: "https://www.w3schools.com/react/react_components.asp",
        description: "This document teaches individual about react components.",
    },
    {
        id: 17,
        topic: "React",
        video_link: null,
        docs_link: "https://www.w3schools.com/react/react_props.asp",
        description: "This document teaches individual about react props.",
    },
    {
        id: 18,
        topic: "React",
        video_link: null,
        docs_link: "https://www.w3schools.com/react/react_jsx.asp",
        description: "This document teaches individual about react JSX.",
    },
    {
        id: 19,
        topic: "UXUI",
        video_link: "https://www.youtube.com/watch?v=TgqeRTwZvIo",
        docs_link: null,
        description: "This video explains the difference between UX and UI.",
    },
    {
        id: 20,
        topic: "UXUI",
        video_link: "https://www.youtube.com/watch?v=FTFaQWZBqQ8",
        docs_link: null,
        description: "This video shows you how to get started with Figma (a useful tool for creating high fidelity wireframes).",
    },
    {
        id: 21,
        topic: "UXUI",
        video_link: "https://www.youtube.com/watch?v=pULLAEmhSho",
        docs_link: null,
        description: "This video teaches you the basics on how to get started with Miro (a useful tool for creating low fidelity wireframes).",
    },
    {
        id: 22,
        topic: "UXUI",
        video_link: null,
        docs_link: "https://www.hubspot.com/make-my-persona",
        description: "This is HubSpot! A great tool for creating user personas and user stories.",
    },
    {
        id: 23,
        topic: "UXUI",
        video_link: null,
        docs_link: "https://careerfoundry.com/en/blog/ux-design/the-difference-between-ux-and-ui-design-a-laymans-guide/",
        description: "This is a beginners guide to UX/UI and the difference between the two.",
    },
    {
        id: 24,
        topic: "UXUI",
        video_link: null,
        docs_link: "https://www.behance.net/galleries/ui-ux/ui-ux",
        description: "This is a documentation on on you to build a good UX.",
    }
];
  
export default resources;